### ISSUE TITLE
section 4.29   this.save.emit(this.categoryForm.value); 

### ISSUE THREAD

**Issue by sshakibi** [danielschmitz/my-sales-aapp#3]
I have checked the code multiple times and I am still getting this error

Error: src/app/categories/form/form.component.ts:32:22 - error TS2345: Argument of type 'Partial<{ id: string | null; name: string | null; description: string | null; }>' is not assignable to parameter of type 'Category'.
  Types of property 'id' are incompatible.
    Type 'string | null | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.

32       this.save.emit(this.categoryForm.value);

thank you in advance

**Comment by danielschmitz** [comment]
to fix this ASAP please change type `Category` to `any`

https://github.com/danielschmitz/my-sales-aapp/compare/main...fix-TS2345

But its not the "better way" to fix this. i will investigate

**Comment by sshakibi** [comment]
Thank you that worked. looking forward to the better way

**Comment by danielschmitz** [comment]
Ok, the "better" way. Always use types in your objetcs :-)

to do this, we need set the value "0" to a number field:

```js
 categoryForm = this.fb.group(
    {
      id: [0],
      name: ['', [Validators.required, Validators.minLength(3)]],
      description: ['']
    }
  )
```

and force the type using "as", in the `save.emit` event:

```js
onSubmit() {
    console.log("submit on form.component.ts", this.categoryForm.value)
    this.save.emit(this.categoryForm.value as Category);
  }
```

Check this [commit](https://github.com/danielschmitz/my-sales-aapp/commit/ed4593f5215349cebe804961bde5575a23ae5c0d) to track the "dirt" way and the "good" way

**Comment by sshakibi** [comment]
thanks a million. Great book by the way, learning a lot.
