### ISSUE TITLE
chapter 5.9 Another way to load async data. 

### ISSUE THREAD

**Issue by sshakibi** [danielschmitz/my-sales-aapp#5]
I am getting the following error , I copied and pasted your files but still am getting the error I also uploaded my project to git hub.

Error: NG0302: The pipe 'async' could not be found in the 'CategoriesLoadingAsyncComponent' component. Verify that it is declared or imported in this module. 

https://github.com/sshakibi/MedTrackPro.git

thanks in advance.

**Comment by danielschmitz** [comment]
Hi,

I believe Angular has made some confusion in your project due to the `main/src/app/src/app` directory. It seems to be duplicated. I cloned your repository, deleted the `main/src/app/src` directory, reorganized the imports, and async worked.

**Comment by sshakibi** [comment]
Thank you so much
